djYMDB/ymdb/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now
from django.core.files.storage import FileSystemStorage

# Create your models here.
@python_2_unicode_compatible
class GenerTag(models.Model):
    name = models.CharField(max_length=70, unique=True, verbose_name='Название')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Collections(models.Model):
    name = models.CharField(max_length=70, unique=True, verbose_name='Название')
    BlockLabel = models.CharField(max_length=30, default='', verbose_name='Подпись для Частей')
    PartLabel = models.CharField(max_length=30, default='', verbose_name='Подпись для Элементов')
    SingleLabel = models.CharField(max_length=100, default='', verbose_name='Подпись для Самостоятельного произведения')
    AgoLabel = models.CharField(max_length=70, default='', verbose_name='Подпись для Даты')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

def update_filename(instance, filename):
    path = "ymdb/static/covers/"
    format = "%s_%s" % (instance.id, filename)
    return os.path.join(path, format)


@python_2_unicode_compatible
class ArtObject(models.Model):
    ART_STATUSES = (
        (-1, 'Без оценки'),
        (0, 'Буду смотреть'),
        (5, 'Отлично'),
        (4, 'Хорошо'),
        (3, 'Приемлемо'),
        (2, 'Плохо'),
        (1, 'Ужасно'),
    )
    ArtCover = models.URLField(verbose_name='Обложка (ссылка на изображние)', blank=True)
    # This strange ArtCoverCahed.upload_to is used beacause only one possible way to serve images in django - through django.staticfiles
    ArtCoverCahed = models.ImageField(verbose_name='Обложка (*.PNG, *.JPEG)', default='', blank=True, upload_to=update_filename)
    ExternalLink = models.URLField(verbose_name='Внешняя ссылка (описание или загрузка)', default='', blank=True)
    ArtTitle = models.CharField('Название', max_length=170)
    ArtSubTitle = models.TextField('Подзаголовок', blank=True, max_length=200)
    UserComment = models.TextField ('Ваш комментарий', blank=True)
    ArtBlocks = models.IntegerField('Томов', default=1, blank=True)
    ArtParts = models.IntegerField('Эпизодов', default=1, blank=True)
    SolidArt = models.BooleanField('Самостоятельное произведение?', default=False)
    UserRating = models.IntegerField('Ваша оценка', choices=ART_STATUSES, default=0)
    ArtGeners = models.ManyToManyField(GenerTag, blank=True, verbose_name='Жанры (Тэги)<br><span class="text-muted small">[Сtrl - несколько]</span>')
    InCollection = models.ForeignKey(Collections, blank=False, default=0, on_delete=models.CASCADE, verbose_name='Коллекция')
    ArtModified = models.DateTimeField('Добавлено', default=now)


    class Meta:
        ordering = ['-ArtModified']

class sysSettings(models.Model):
    HEAD_THEMES = (
        ('navbar-dark bg-dark', 'Тёмная'),
        ('navbar-light bg-light', 'Светлая'),
        ('navbar-light alert-secondary border-bottom border-secondary', 'Серая'),
        ('navbar-light alert-primary border-bottom border-primary', 'Голубая'),
        ('navbar-light alert-success border-bottom border-success', 'Зеленая'),
        ('navbar-light alert-warning border-bottom border-warning', 'Желатая'),
        ('navbar-light alert-danger border-bottom border-danger', 'Красная'),
    )
    theUser = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    pageStep = models.IntegerField(verbose_name='Отбражать по Х карт:', default=0)
    navTheme = models.CharField(verbose_name='Тема тулбара', choices=HEAD_THEMES, default=HEAD_THEMES[0], max_length=200)

class guestTestimonilas(models.Model):
    ArtBind = models.ForeignKey(ArtObject, on_delete=models.CASCADE)
    tsName = models.TextField(verbose_name='', blank=True, max_length=100)
    tsText = models.TextField(verbose_name='', blank=True)
    tsDate = models.DateTimeField(default=now)
    isAdmin = models.IntegerField(default=-1)

    def __str__(self):
        return self.tsName

djYMDB/templates/index.html
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="manifest" href="{% static 'manifest.json' %}">

    <title>{% block mytitle %}{% endblock %}</title>

    <!-- Custom styles for this template -->
    <link href="{% static 'album.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-datetimepicker/css/bootstrap-datetimepicker.css' %}" rel="stylesheet">

    <!-- Fontawesome -->
    <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet">

    {% block hScripts %} {% endblock %}

</head>

<body>

<!-- This small check wil try to get user's theme, if possible -->

<nav class="navbar {% if uStyle %}{{ uStyle }}{% else %}navbar-dark bg-dark{% endif %}
    shadow d-flex justify-content-around align-content-center sticky-top ">
    {% if "navbar-light" in uStyle %}
        {% static 'site_logo-dk.png' as siteLogo %}
    {% else %}
        {% static 'site_logo.png' as siteLogo %}
    {% endif %}

    <a href="/" class="navbar-brand">
        <img src="{{ siteLogo }}">
    </a>

    <div class="d-flex justify-content-center" style="padding-bottom: 5px">
        {% block myheading %}{% endblock %}
    </div>
    <div class="d-flex flex-wrap justify-content-center row btn-group">
        <button class="btn btn-outline-info" data-toggle="modal" data-target="#mSearch" title="Поиск">
            <span class="fas fa-search"></span>
        </button>
        {% block subPages %}{% endblock %}
    </div>

</nav>


<main role="main">
    {% block mycontent %}{% endblock %}
    {% if sForm %}
        <div class="modal fade" tabindex="-2" role="dialog" id="changeSetting" aria-hidden="true">
            <form class="modal-dialog" role="form" action="{% url 'chSett' %}" method="post">
                <div class="modal-content">
                    <div class="modal-header font-weight-bold text-primary">Настройки</div>
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col">{{ sForm.pageStep|as_crispy_field }}</div>
                            <div class="col">{{ sForm.navTheme|as_crispy_field }}</div>
                        </div>
                        <div class="alert alert-warning">
                            <span class="fas fa-exclamation-triangle"></span>
                            Будьте внимательны! Фильтры будут <b>сброшены</b>!
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="Сохранить">
                        <span class="btn btn-secondary" data-dismiss="modal">Отмана</span>
                    </div>
                </div>
            </form>
        </div>
    {% endif %}
    <div class="modal fade" tabindex="-3" role="dialog" id="mSearch" aria-hidden="true">
        <form class="modal-dialog" role="form" action="{% url 'ArtList' %}" method="post" target="_blank">
            <div class="modal-content">
                <div class="modal-header font-weight-bold text-primary">Поиск (Загловок, Подзаголовок)</div>
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col"><input class="form-control" type="text" name="kw" value="{{ kWord }}"></div>
                    </div>
                    <hr>
                    <div class="alert alert-warning">
                        <span class="fas fa-exclamation-triangle"></span>
                        Будьте внимательны! Фильтры будут <b>сброшены</b>!
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Искать">
                    <span class="btn btn-secondary" data-dismiss="modal">Отмана</span>
                </div>
            </div>
        </form>
    </div>
</main>

<footer class="text-muted">
    <div class="container" style="margin: 0px 15px;">
        <p class="float-right">
            <a href="#">&uparrow; НАВЕРХ &uparrow;</a>
        </p>
        <span class="small">
            <span class="small">
        <p>Создано <a href="https://scadsdnd.net/" target="_blank">SCAD's Design & Develop</a>.</p>
        <p>Stylized with <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a> & <a
                href="https://fontawesome.com/" target="_blank">FontAwesome</a>.</p>
        <p>Powered by <a href="https://www.djangoproject.com/" target="_blank">Django</a>.</p>
                </span>
        </span>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'bootstrap/js/jquery-3.3.1.min.js' %}"></script>
<script>window.jQuery || document.write('<script src="{% static 'bootstrap/js/jquery-slim.min.js' %}"><\/script>')</script>

<script src="{% static 'bootstrap-datetimepicker/js/bootstrap-datetimepicker.js' %}"></script>
<script src="{% static 'bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.ru.js' %}"></script>

<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'bootstrap/js/holder.min.js' %}"></script>

<script type="text/javascript">

    // Ajax Handler for modalLogout
    $('#logoutModal').on('show.bs.modal', function (evt) {
        $('.modal-footer #sendPass').click(function () {
            $.ajax({
                url: '{% url 'async_chpass' %}',
                data: {
                    upass: $('.modal-body #uPass').val(),
                    uname: '{{ user.username }}'
                },
                dataType: 'json',
                success: function (data) {
                    // response handler here with data.vars
                    $('#logoutModal').modal('hide');
                    window.location = "/"
                }
            })
        });
    });
    //
    var pkActive = 0;
    $('[id^="tsList_"]').on('show.bs.modal', function (evt) {
        pkActive = $(this).attr('id').split('_')[1];
        $.ajax({
            url: '{% url 'async_tsLoad' %}',
            data: {
                aIdent: pkActive
            },
            dataType: 'json',
            success: function (data) {
                // response handler here with data.vars
                respTS = JSON.parse(data);

                var tsList = '';
                for (var kn = 0; kn < respTS.length; kn++) {

                    if (respTS[kn].fields.isAdmin >= 0) {
                        var lblColor = 'text-danger';
                    } else {
                        var lblColor = 'text-primary';
                    }

                    tsList +=
                        '<div class="row" id="tsLN_' + respTS[kn].pk + '" style="border-bottom: solid 1px silver">' +
                        '   <div class="col">' +
                        '       <span class="' + lblColor + '">' + respTS[kn].fields.tsName + ':</span>' +
                        '       <br>' +
                        respTS[kn].fields.tsText +
                        {% if user.is_authenticated %}
                            '       <a class="btn btn-sm btn-outline-danger float-right tsDelBtn" tsAID="'+respTS[kn].pk+'">'+
                            '           <span class="far fa-trash-alt btn-outline-danger"></span>' +
                            '       </a>'+
                        {% endif %}
                        '   <br>' +
                        '       <span class="text-muted small">' + respTS[kn].fields.tsDate + '</span>' +
                        '   </div>\n' +
                        '</div>';

                }
                $('#tsList_' + pkActive + " .modal-body").html(tsList);

                // Ajax delTestimonial
                $('.tsDelBtn').click(function () {
                    pkATS = $(this).attr('tsAID');
                    $.ajax({
                        url: '{% url 'async_tsDel' %}',
                        data: {
                            aIdent: pkATS
                        },
                        dataType: 'json',
                        success: function (data) {
                            $('#tsLN_' + pkATS).hide();
                            var nmV = Number($('#tsNM_' + pkActive).text()) - 1
                            $('#tsNM_' + pkActive).text(nmV);
                        }
                    })
                });

                if(respTS.length==0){
                    $('#tsList_' + pkActive + " .modal-body").html('<div class="text-muted font-italic text-center">- Пока нет отзывов -</div>');
                }

            }
        })
    });
    // Ajax Handler for modalTestimonial
    $('#testimonialModal').on('show.bs.modal', function (evt) {
        $('.modal-footer #sendTsMsg').click(function () {
            $.ajax({
                url: '{% url 'async_tsSend' %}',
                data: {
                    gName: $('.modal-body #gName').val(),
                    gText: $('.modal-body #gText').val(),
                    uName: '{{ user.username }}',
                    aIdent: pkActive
                },
                dataType: 'json',
                beforeSend: function () {
                    $('#testimonialModal').modal('hide');
                },
                success: function (data) {
                    // response handler here with data.vars

                    var nmV = Number($('#tsNM_' + pkActive).text()) + 1
                    $('#tsNM_' + pkActive).text(nmV);
                }
            })
        });
    });


    $('#id_ArtModified').datetimepicker({
        format: "dd.mm.yyyy hh:ii:ss",
        todayBtn: true,
        todayHighlight: true
    });


    // This small block will loop through associative massive, provided by block,
    // and extract icon classes corresponding to crispy form field name label.
    var formIcons = new Array();
    {% block formIconsJS %}{% endblock %}
    $('label.col-form-label').each(function () {
        fName = $(this).attr('for');
        $(this).html('<span class="' + formIcons[fName] + '" style="padding-right: 5px"></span>' + $(this).html());
    });
</script>
</body>
</html>