djYMDB/ymdb/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now
from django.core.files.storage import FileSystemStorage

# Create your models here.
@python_2_unicode_compatible
class GenerTag(models.Model):
    name = models.CharField(max_length=70, unique=True, verbose_name='Название')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Collections(models.Model):
    name = models.CharField(max_length=70, unique=True, verbose_name='Название')
    BlockLabel = models.CharField(max_length=30, default='', verbose_name='Подпись для Частей')
    PartLabel = models.CharField(max_length=30, default='', verbose_name='Подпись для Элементов')
    SingleLabel = models.CharField(max_length=100, default='', verbose_name='Подпись для Самостоятельного произведения')
    AgoLabel = models.CharField(max_length=70, default='', verbose_name='Подпись для Даты')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

def update_filename(instance, filename):
    path = "ymdb/static/covers/"
    format = "%s_%s" % (instance.id, filename)
    return os.path.join(path, format)


@python_2_unicode_compatible
class ArtObject(models.Model):
    ART_STATUSES = (
        (-1, 'Без оценки'),
        (0, 'Буду смотреть'),
        (5, 'Отлично'),
        (4, 'Хорошо'),
        (3, 'Приемлемо'),
        (2, 'Плохо'),
        (1, 'Ужасно'),
    )
    ArtCover = models.URLField(verbose_name='Обложка (ссылка на изображние)', blank=True)
    # This strange ArtCoverCahed.upload_to is used beacause only one possible way to serve images in django - through django.staticfiles
    ArtCoverCahed = models.ImageField(verbose_name='Обложка (*.PNG, *.JPEG)', default='', blank=True, upload_to=update_filename)
    ExternalLink = models.URLField(verbose_name='Внешняя ссылка (описание или загрузка)', default='', blank=True)
    ArtTitle = models.CharField('Название', max_length=170)
    ArtSubTitle = models.TextField('Подзаголовок', blank=True, max_length=200)
    UserComment = models.TextField ('Ваш комментарий', blank=True)
    ArtBlocks = models.IntegerField('Томов', default=1, blank=True)
    ArtParts = models.IntegerField('Эпизодов', default=1, blank=True)
    SolidArt = models.BooleanField('Самостоятельное произведение?', default=False)
    UserRating = models.IntegerField('Ваша оценка', choices=ART_STATUSES, default=0)
    ArtGeners = models.ManyToManyField(GenerTag, blank=True, verbose_name='Жанры (Тэги)<br><span class="text-muted small">[Сtrl - несколько]</span>')
    InCollection = models.ForeignKey(Collections, blank=False, default=0, on_delete=models.CASCADE, verbose_name='Коллекция')
    ArtModified = models.DateTimeField('Добавлено', default=now)


    class Meta:
        ordering = ['-ArtModified']

class sysSettings(models.Model):
    HEAD_THEMES = (
        ('navbar-dark bg-dark', 'Тёмная'),
        ('navbar-light bg-light', 'Светлая'),
        ('navbar-light alert-secondary border-bottom border-secondary', 'Серая'),
        ('navbar-light alert-primary border-bottom border-primary', 'Голубая'),
        ('navbar-light alert-success border-bottom border-success', 'Зеленая'),
        ('navbar-light alert-warning border-bottom border-warning', 'Желатая'),
        ('navbar-light alert-danger border-bottom border-danger', 'Красная'),
    )
    theUser = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    pageStep = models.IntegerField(verbose_name='Отбражать по Х карт:', default=0)
    navTheme = models.CharField(verbose_name='Тема тулбара', choices=HEAD_THEMES, default=HEAD_THEMES[0], max_length=200)

class guestTestimonilas(models.Model):
    ArtBind = models.ForeignKey(ArtObject, on_delete=models.CASCADE)
    tsName = models.TextField(verbose_name='', blank=True, max_length=100)
    tsText = models.TextField(verbose_name='', blank=True)
    tsDate = models.DateTimeField(default=now)
    isAdmin = models.IntegerField(default=-1)

    def __str__(self):
        return self.tsName

djYMDB/ymdb/forms.py
from django.forms import ModelForm, Textarea, SelectMultiple, RadioSelect
from .models import ArtObject, Collections, GenerTag, sysSettings


class ArtForm(ModelForm):
    class Meta:
        model = ArtObject
        fields = '__all__'
        widgets = {
            'UserRating': RadioSelect(attrs={'style':'margin-right:5px'}),
            'ArtSubTitle': Textarea(attrs={'style':'height:65px'}),
            'UserComment': Textarea(attrs={'style': 'height:130px'}),
            'ArtGeners': SelectMultiple(attrs={'style': 'height:615px'}, choices=ArtObject.ART_STATUSES, ),
        }

class CollectionForm(ModelForm):
    class Meta:
        model = Collections
        fields = '__all__'
        exclude = ['artobject']


class GenerTagForm(ModelForm):
    class Meta:
        model = GenerTag
        tempFiled = [f.name for f in model._meta.get_fields()]
        tempFiled.remove('artobject')
        fields = tempFiled

class FormSettings(ModelForm):
    class Meta:
        model = sysSettings
        fields = '__all__'
        exclude = ['theUser']

djYMDB/ymdb/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.core import serializers

from .models import ArtObject, Collections, GenerTag, sysSettings, guestTestimonilas
from .forms import ArtForm, CollectionForm, GenerTagForm, FormSettings

# Create your views here.
def arts_list(req, gid=-1, cid=-1, pg=0):

    try:
        uSettigs = sysSettings.objects.all()[0]
    except LookupError:
        newSet = sysSettings(theUser = User.objects.all[0], pageStep = 6, navTheme = 'navbar-dark bg-dark')
        newSet.save()
        uSettigs = sysSettings.objects.all()[0]

    setForm = FormSettings(instance=uSettigs)
    pageStep = uSettigs.pageStep
    uStyle = uSettigs.navTheme

    allCollect = Collections.objects.all()
    req.session['uStyle'] = uStyle
    req.session['uPage'] = pg
    req.session['uGenre'] = gid
    req.session['uCollect'] = cid
    rkWord = ''

    if gid > -1:
        allArts = ArtObject.objects.filter(ArtGeners=gid)[(pg*pageStep):(pageStep+(pg*pageStep))]
        nfArts = ArtObject.objects.filter(ArtGeners=gid)
    elif cid > -1:
        allArts = ArtObject.objects.filter(InCollection=cid)[(pg*pageStep):(pageStep+(pg*pageStep))]
        nfArts = ArtObject.objects.filter(InCollection=cid)
    elif req.method == 'POST':
        allArts = ArtObject.objects.filter(
            Q(ArtTitle__contains=req.POST.get('kw', None)) | Q(ArtSubTitle__contains=req.POST.get('kw', None))
        )[(pg * pageStep):(pageStep + (pg * pageStep))]
        nfArts = ArtObject.objects.filter(
            Q(ArtTitle__contains=req.POST.get('kw', None))|Q(ArtSubTitle__contains=req.POST.get('kw', None))
        )
        rkWord = req.POST.get('kw', None);
    else:
        allArts = ArtObject.objects.all()[(pg*pageStep):(pageStep+(pg*pageStep))]
        nfArts = ArtObject.objects.all()

    #print(pageStep, ':',  pg*pageStep)
    #print(req.POST.get('kw', None))

    VContext = {'artsList': allArts,
                'collsList': allCollect,
                'pages':range(0, nfArts.count()//pageStep+1),
                'uStyle': req.session['uStyle'],
                'active': req.session['uPage'],
                'gid': req.session['uGenre'],
                'cid': req.session['uCollect'],
                'kWord': rkWord,
                'sForm' : setForm}

    return render(req, 'artList.html', VContext)

#@login_required
def art_add(req, refF=-1):
    if req.method == 'POST':
        myForm = ArtForm(data = req.POST, files=req.FILES)
        if myForm.is_valid():
            thisArt = myForm.save(commit=False)
            thisArt.save()
            myForm.save_m2m()
            if refF == 1:
                return redirect('genFilter', gid=req.session['uGenre'], pg=req.session['uPage'])
            elif refF == 2:
                return redirect('collFilter', cid=req.session['uCollect'], pg=req.session['uPage'])
            else:
                return redirect('pageU', pg=req.session['uPage'])
    else:
        myForm = ArtForm
        #myForm.fields['ArtSubTitle'].widget.attrs = {'style':'height:110px'}
        #myForm.fields['ArtGeners'].widget.attrs = {'style':'height:295px'}
    VContext = {'formData':myForm,
                'formMode':True,
                'uStyle': req.session['uStyle'],
                'refFS':refF}
    return render(req, 'artForm.html', VContext)

#@login_required
def art_edit(req, pk, refF=-1, rtg=-1, rpg=0):
    thisArt = get_object_or_404(ArtObject, pk=pk)
    if req.method == 'POST':
        myForm = ArtForm(instance=thisArt, data=req.POST, files=req.FILES)
        if myForm.is_valid():
            myForm.save()
            if refF == 1:
                return redirect('genFilter', gid=rtg, pg=rpg)
            elif refF == 2:
                return redirect('collFilter', cid=rtg, pg=rpg)
            else:
                return redirect('pageU', pg=rpg)
    else:
        myForm = ArtForm(instance=thisArt)
        #myForm.fields['ArtSubTitle'].widget.attrs = {'style':'height:110px'}
        #myForm.fields['ArtGeners'].widget.attrs = {'style':'height:295px'}
    VContext = {'formData':myForm, 'formMode':False,
                'refFS':refF, 'rtgS':rtg, 'rpgS':rpg,
                'uStyle': req.session['uStyle'],}
    return render(req, 'artForm.html', VContext)

#@login_required()
def prop_edit(req, ref, pky=-1):
    if ref == 1:
        if pky == -1:
            if req.method == 'POST':
                cForm = CollectionForm(data=req.POST)
            else:
                cForm = CollectionForm
        else:
            if req.method == 'POST':
                cForm = CollectionForm(instance=Collections.objects.get(pk=pky), data=req.POST)
            else:
                cForm = CollectionForm(instance=Collections.objects.get(pk=pky))
        allColl = Collections.objects.all()
        isCol = True

    if ref == 2:
        if pky == -1:
            if req.method == 'POST':
                cForm = GenerTagForm(data=req.POST)
            else:
                cForm = GenerTagForm
        else:
            if req.method == 'POST':
                cForm = GenerTagForm(instance=GenerTag.objects.get(pk=pky), data=req.POST)
            else:
                cForm = GenerTagForm(instance=GenerTag.objects.get(pk=pky))
        allColl = GenerTag.objects.all()
        isCol = False

    if req.method == 'POST':
        if cForm.is_valid():
            thisCol = cForm.save(commit=False)
            thisCol.save()
            cForm.save_m2m()
            return redirect('propEdit', ref=ref)

    VContext = {'theForm':cForm, 'AllList':allColl,
                'isColl':isCol, 'delAct': ref,
                'uStyle': req.session['uStyle']}
    return render(req, 'collList.html', VContext)


#@login_required()
def delSomething(req, pk, ref, refF=-1, rtg=-1, rpg=0):
    if ref == 0:
        """ This is request from card (bookmark) """
        refData = ArtObject.objects.get(pk=pk)
    if ref == 1:
        """ This is request from collections """
        refData = Collections.objects.get(pk=pk)
        refRedir = 1
    if ref == 2:
        """ This is request from genres """
        refData = GenerTag.objects.get(pk=pk)
        refRedir = 2
    refData.delete()
    if ref == 0:
        if refF == 1:
            return redirect('genFilter', gid=rtg, pg=rpg)
        elif refF == 2:
            return redirect('collFilter', cid=rtg, pg=rpg)
        else:
            return redirect('pageU', pg=rpg)

    else:
        return redirect('propEdit', ref=refRedir)

#@login_required
def chpass (req):
    usr = User.objects.get(username=req.GET.get('uname', None))
    usr.set_password(req.GET.get('upass', None))
    usr.save()

    data = {'vars':0}
    return JsonResponse(data)

def chSettings(req):

    uSettings = get_object_or_404(sysSettings, theUser=req.user.pk)
    uSetForm = FormSettings(instance=uSettings, data=req.POST)
    if uSetForm.is_valid:
        uSetForm.save()
        return redirect('ArtList')

def sendTs(req):
    aTg = ArtObject.objects.get(pk=req.GET.get('aIdent', int))
    newTs = guestTestimonilas.objects.create(ArtBind=aTg)
    newTs.tsName = req.GET.get('gName', None)
    newTs.tsText = req.GET.get('gText', None)
    if req.GET.get('uName', None) != '':
        newTs.isAdmin = 1
    newTs.save()

    data = {'vars': 0}
    return JsonResponse(data)

def delTS(req):
    tsWork = guestTestimonilas.objects.get(pk=req.GET.get('aIdent', int))
    tsWork.delete()

    data = {'vars': 0}
    return JsonResponse(data)

def dynaTSLoad(req):
    tsList = guestTestimonilas.objects.filter(ArtBind=req.GET.get('aIdent', int))
    tsData = serializers.serialize('json', tsList)
    return JsonResponse(tsData, content_type='application/json', safe=False)

def getArtInfo(req, pk):
    artData = thisArt = get_object_or_404(ArtObject, pk=pk)
    return render(req, 'artPage.html', {'sArt':artData, 'shareUri':req.build_absolute_uri()});

djYMDB/ymdb/templates/artList.html
{% extends 'index.html' %}

{% block mytitle %} YMDB {% endblock %}
{% block myheading %}
    <span class="row">
    {% for oneCol in collsList %}
        <a href="{% url 'collFilter' cid=oneCol.pk pg=0 %}" style="border-radius: 0px"
           class="col btn btn-outline-primary {% if oneCol.pk == cid %}active{% endif %}">
            <span class="fas fa-book"></span>&nbsp;
            {{ oneCol.name }}
        </a>
    {% endfor %}
    </span>
{% endblock %}

{% block subPages %}
    <a href="{% if gid != -1 %}
        {% url 'ArtAdd' refF=1 %}
    {% elif cid != -1 %}
        {% url 'ArtAdd' refF=2 %}
    {% else %}
        {% url 'ArtAdd' refF=0 %}
    {% endif %}" class="btn btn-outline-info" title="Добавить">
        <span class="fas fa-plus-square"></span>
    </a>
    <button class="btn btn-outline-info" data-toggle="modal" data-target="#changeSetting" title="Настройки">
        <span class="fas fa-cogs"></span>
    </button>
    <a href="{% url 'propEdit' 1 %}" class="btn btn-outline-success" title="Коллекции">
        <span class="fas fa-book"></span>
    </a>
    <a href="{% url 'propEdit' 2 %}" class="btn btn-outline-success" title="Жанры">
        <span class="fas fa-puzzle-piece"></span>
    </a>
{% endblock %}

{% block mycontent %}
    <div class="d-flex flex-wrap justify-content-center">
        {% if kWord != '' %}
            <div class="card shadow-sm bg-light" style="width: 100%">
                <div class="card-header">
                    <p class="card-text text-center">
                        Поиск по: <span class="font-weight-bold">{{ kWord }}</span>
                    </p>
                </div>
            </div>
        {% endif %}
        {% for artDesc in artsList %}
            <div class="card shadow-sm align-self-start" style="width: 12rem; margin: 6px">
                {% if artDesc.ArtCoverCahed %}
                    <img class="card-img-top" src="{{ artDesc.ArtCoverCahed.url|cut:"ymdb" }}"
                         alt="{{ artDesc.ArtTitle }} Cover">
                {% elif artDesc.ArtCover %}
                    <img class="card-img-top" src="{{ artDesc.ArtCover }}" alt="{{ artDesc.ArtTitle }} Cover">
                {% else %}
                    <img class="card-img-top"
                         data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Нет Обложки" alt="">
                {% endif %}
                {% if artDesc.UserRating >= 0 %}
                    <ul class="list-group list-group-flush" title="Моя Оцека">
                        <li class="list-group-item d-flex justify-content-center font-weight-bold rated_{{ artDesc.UserRating }}">
                            <span class="fas fa-star-half-alt" style="padding-right: 5px"></span>
                            {{ artDesc.get_UserRating_display }}
                        </li>
                    </ul>
                {% endif %}
                <div class="card-body align-content-center" style="padding-bottom:0px">
                    <h5 class="card-title" style="font-size: medium; text-align: center" title="Название">
                        {% if artDesc.ExternalLink != '' %}
                            <a href="{{ artDesc.ExternalLink }}" target="_blank" class="align-self-center"
                               title="Ссылка на внешнее описание или загрузку">
                                {{ artDesc.ArtTitle }}
                            </a>
                        {% else %}
                            <span class="align-self-center font-italic"
                                  title="Нет внешней ссылки. Напишите об этом в отзыве">
                          {{ artDesc.ArtTitle }}
                          </span>
                        {% endif %}
                    </h5>
                    <h6 class="card-title mb-2 text-muted small " title="Подзаголовк (Перевод)">
                        {% if artDesc.ArtSubTitle %} {{ artDesc.ArtSubTitle|linebreaksbr }} {% endif %}
                    </h6>

                </div>
                <div class="card-body text-sm-center btn-group d-flex" style="padding: 0px">
                    {% if artDesc.UserComment != '' %}
                    <a href="{% url 'artPage' artDesc.pk %}"
                       class="btn btn-light btn-sm flex-fill rounded-0"
                        title="Прочиать описание/рецезию от автора каталога">
                            Описание
                    </a>
                    {% else %}
                        <div class="btn btn-light btn-sm flex-fill rounded-0 disabled" title="Пока нет описания/рецензии">
                            <strike>Описание</strike>
                        </div>
                    {% endif %}
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item list-group-item-light" title="{{ artDesc.InCollection.SingleLabel }}">
                        {% if artDesc.SolidArt %}
                            {% if artDesc.InCollection.SingleLabel != '' %}
                                <strong> {{ artDesc.InCollection.SingleLabel|truncatechars:16 }} </strong>
                            {% else %}
                                <strong> Самостоят. П. </strong>
                            {% endif %}
                        {% else %}
                            <div class="row">
                                <div class="col-6" title="{% if artDesc.InCollection != '' %}{{ artDesc.InCollection.BlockLabel }}:{% else %}Части:{% endif %}">
                                    <span class="text-primary font-weight-bold">
                                        <i class="fas fa-tape"></i> {{ artDesc.ArtBlocks }}
                                    </span>
                                </div>
                                <div class="col-6" title="{% if artDesc.InCollection != '' %}{{ artDesc.InCollection.PartLabel }}:{% else %}Элементы:{% endif %}">
                                    <span class="text-primary font-weight-bold">
                                        <span class="fas fa-film"></span> {{ artDesc.ArtParts }}
                                    </span>
                                </div>
                            </div>
                        {% endif %}
                    </li>
                    {% if artDesc.ArtGeners.count %}
                        <li class="list-group-item list-group-item-light" title="Жанры">
                        <span class="small d-flex flex-wrap">
                        {% for generTag in artDesc.ArtGeners.all %}
                            <a href="{% url 'genFilter' gid=generTag.pk pg=active %}">
                                <span class="fas fa-puzzle-piece"></span>&nbsp;
                                <span class="{% if generTag.pk == gid %}badge-primary{% endif %}">
                                {{ generTag.name }},</span>&nbsp;
                            </a>
                        {% endfor %}
                        </span>
                        </li>
                    {% endif %}

                    <li class="list-group-item list-group-item-light text-muted"
                        title="{% if artDesc.InCollection != '' %}{{ artDesc.InCollection.AgoLabel }}:{% else %}Просмотрено:{% endif %}">
                        <span class="fas fa-eye"></span>
                        <span class="small"> {{ artDesc.ArtModified|date:'d.m.Y H:i' }} </span>
                    </li>


                        <div class="list-group-item btn-group d-flex justify-content-center align-items-center"
                             style="padding: 3px">

                            <a class="btn btn-sm btn-outline-primary" href="{% if gid != -1 %}
                        {% url 'ArtEditAdv' pk=artDesc.pk refF=1 rtg=gid rpg=active %}
                        {% elif cid != -1 %}
                        {% url 'ArtEditAdv' pk=artDesc.pk refF=2 rtg=cid rpg=active %}
                        {% else %}
                        {% url 'ArtEdit' pk=artDesc.pk rpg=active %}
                        {% endif %}">
                                <span class="fas fa-edit"></span> Изменить
                            </a>
                            <a class="btn btn-sm btn-outline-danger" href="{% if gid != -1 %}
                        {% url 'delActAdv' pk=artDesc.pk ref=0 refF=1 rtg=gid rpg=active %}
                        {% elif cid != -1 %}
                        {% url 'delActAdv' pk=artDesc.pk ref=0 refF=2 rtg=cid rpg=active %}
                        {% else %}
                        {% url 'delAct' pk=artDesc.pk ref=0 rpg=active %}
                        {% endif %}">
                                <span class="fas fa-trash-alt"></span> Удалить
                            </a>

                        </div>


                </ul>
            </div>

        {% empty %}

            <div class="card shadow-sm" style="width: 100%; margin-bottom: 10px">
                <div class="card-body">
                    <p class="card-text text-center">Нет элементов</p>
                </div>
            </div>

        {% endfor %}
    </div>

    {% if pages|last > 0 %}
        <ul class="pagination d-flex justify-content-center flex-wrap">
            <li class="page-item {% if active <= 0 %} disabled {% endif %}">
                <a class="page-link" href="{% if active <= 0 %}#{% else %}
      {% if gid != -1 %}
        {% url 'genFilter' gid=gid pg=active|add:"-1" %}
        {% elif cid != -1 %}
        {% url 'collFilter' cid=cid pg=active|add:"-1" %}
        {% else %}
        {% url 'pageU' pg=active|add:"-1" %}
    {% endif %}
    {% endif %}" tabindex="-1">&laquo;</a>
            </li>
            {% for indA in pages %}
                <li class="page-item {% if indA == active %} active {% endif %}">
                    <a class="page-link" href="{% if gid != -1 %}
        {% url 'genFilter' gid=gid pg=indA %}
        {% elif cid != -1 %}
        {% url 'collFilter' cid=cid pg=indA %}
        {% else %}
        {% url 'pageU' pg=indA %}
    {% endif %}">
                        {{ indA|add:"1" }}</a>
                </li>
            {% endfor %}
            <li class="page-item {% if active|add:1 >= pages|last|add:1 %} disabled {% endif %}">
                <a class="page-link" href="{% if gid != -1 %}
        {% url 'genFilter' gid=gid pg=active|add:"1" %}
        {% elif cid != -1 %}
        {% url 'collFilter' cid=cid pg=active|add:"1" %}
        {% else %}
        {% url 'pageU' pg=active|add:"1" %}
    {% endif %}">&raquo;</a>
            </li>
        </ul>
    {% endif %}

{% endblock %}

djYMDB/ymdb/templates/artPage.html
{% extends 'index.html' %}

{% block mytitle %} [YMDB] {{ sArt.ArtTitle }} {% endblock %}
{% block myheading %}
    <span class="row">
        <a href="/" style="border-radius: 0px"
           class="col btn btn-outline-primary">
            <span class="fas fa-level-up-alt fa-flip-horizontal"></span>&nbsp;Назад к катлогу&nbsp;<span class="fas fa-level-up-alt"></span>
        </a>
    </span>
{% endblock %}
{% block subPages %}{% endblock %}
{% block hScripts %}
    <!-- Facebook Crawler parameters -->
    <meta property="og:url"                content="{{ shareUri }}" />
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="[YMDB] {{ sArt.ArtTitle }}" />
    <meta property="og:description"        content="{{ sArt.UserComment|truncatewords:100 }}" />
{% endblock %}

{% block mycontent %}
    <div class="container" style="margin: 0px 15px; min-width: calc(100% - 30px)">
        <h1 class="text-primary display-4"> {{ sArt.ArtTitle }} </h1>
        <div class="d-flex flex-row align-items-start">
            {% if sArt.ArtCoverCahed %}
                <img class="card img-thumbnail rounded" style="min-width: 250px" src="{{ sArt.ArtCoverCahed.url|cut:"ymdb" }}"
                     alt="{{ sArt.ArtTitle }} Cover">
            {% elif sArt.ArtCover %}
                <img class="card img-thumbnail rounded" src="{{ sArt.ArtCover }}" alt="{{ sArt.ArtTitle }} Cover">
            {% else %}
                <img class="card img-thumbnail rounded"
                     data-src="holder.js/20px250?theme=thumb&bg=55595c&fg=eceeef&text=Нет Обложки" alt="">
            {% endif %}
            <div class="lead ml-3">
                {{ sArt.UserComment }}
                <hr>
                <div class="text-muted" style="font-size: 15px">
                    {% if sArt.ArtSubTitle %}
                        <span class="fas fa-star-half-alt"></span> <span class="font-weight-bold"> Альт. названия: </span>
                        {{ sArt.ArtSubTitle }}
                    {% endif %}
                    <br>
                    <span class="fas fa-tape"></span> <span class="font-weight-bold"> Состав: </span>
                    {% if sArt.SolidArt %}
                        {% if sArt.InCollection.SingleLabel != '' %}
                            <strong> {{ sArt.InCollection.SingleLabel }} </strong>
                        {% else %}
                            <strong> Самостоятельное Произвдение </strong>
                        {% endif %}
                    {% else %}
                        {{ sArt.ArtBlocks }} {% if sArt.InCollection != '' %}{{ sArt.InCollection.BlockLabel }}{% else %}Частей{% endif %},
                        {{ sArt.ArtParts }} {% if sArt.InCollection != '' %}{{ sArt.InCollection.PartLabel }}{% else %}Элементов{% endif %}
                    {% endif %}
                    <br>
                    {% if sArt.ArtGeners.count %}
                        <span class="fas fa-puzzle-piece"></span> <span class="font-weight-bold"> Жанры: </span>
                        {% for generTag in sArt.ArtGeners.all %}
                            {{ generTag.name }},
                        {% endfor %}
                    {% endif %}
                    <br>
                    {% if sArt.UserRating >= 0 %}
                        <span class="fas fa-star-half-alt"></span> <span class="font-weight-bold"> Оценка: </span>
                        <span class="font-weight-bold rated_{{ sArt.UserRating }}" >
                        &nbsp;{{ sArt.get_UserRating_display }}&nbsp;
                        </span>
                    {% endif %}
                    <br>

                </div>
            </div>
        </div>
    </div>
{% endblock %}